#!/bin/sh
# cbus_ramp: example script for publishing a "light ramp" message for cmqttd
#
# Usage: cbus_ramp <group_address> <duration> <level>
#
# NOTE: This presumes that you have an MQTT server running on `localhost`, without authentication.
# You will need to adapt this script to your local installation, or create
# `~/.config/mosquitto_pub` with additional options; see `man mosquitto_pub` for details.

if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
    echo "Usage: $0 <group_address> <duration> <level>"
    echo "To turn ramp group address 1 over 20 seconds to half brightness, run:"
    echo "   $0 1 20 127"
    exit 1
fi

mosquitto_pub -q 1 -t "homeassistant/light/cbus_${1}/set" -m \
    "{ \"state\": \"ON\", \"transition\": $2, \"brightness\": $3 }"
