#!/bin/sh
# cbus_on: example script for publishing a "light on" message for cmqttd
#
# Usage: cbus_on <group_address>
#
# NOTE: This presumes that you have an MQTT server running on `localhost`, without authentication.
# You will need to adapt this script to your local installation, or create
# `~/.config/mosquitto_pub` with additional options; see `man mosquitto_pub` for details.

if [[ -z "$1" ]]; then
    echo "Usage: $0 <group_address>"
    echo "eg: to turn on group address 1, run:"
    echo "   $0 1"
    exit 1
fi

mosquitto_pub -q 1 -t "homeassistant/light/cbus_${1}/set" -m '{ "state": "ON" }'
