#!/bin/sh
# cbus_off: example script for publishing a "light off" message for cmqttd
#
# Usage: cbus_off <group_address>
#
# NOTE: mosquitto_pub presumes that you have an MQTT server running on localhost, without
# authentication. You will need to create `~/.config/mosquitto_pub` for additional options.
# See the mosquitto_pub man page for details.

if [[ -z "$1" ]]; then
    echo "Usage: $0 <group_address>"
    echo "eg: to turn off group address 1, run:"
    echo "   $0 1"
    exit 1
fi

mosquitto_pub -q 1 -t "homeassistant/light/cbus_${1}/set" -m '{ "state": "OFF" }'
