#!/bin/sh

# You need to specify arguments pointing to where the CBus PCI is located.

# To use a TCP PCI, for example:
#DAEMON_ARGS="-t localhost:10001"

# To use a serial/USB PCI, for example:
DAEMON_ARGS="-s /dev/ttyUSB0"

# If you have many USB serial converters connected to the system, it may help
# to refer to them by id if you use udev:
#DAEMON_ARGS="-s /dev/serial/id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0"

